### PR TITLE
chore: #1326 Data generation script for load testing

### PR DESCRIPTION
**Pull request by basilv**
Generate ~1 year of fake data for load testing. Tested loading into database but haven't tested with running application yet.

### CODE REVIEW

**Comment by ianliuwk1019** [comment]
Hi @basilv ,
Not a comment, just FYI.
I took your data.sql and placed them into `flyway/local_sql` folder to run migration. Despite initial warning, it was run successfully.
image
With fam_user table loaded with:
image

**Comment by basilv** [comment]
Sounds like there were no performance issues running locally, so I think this PR is ready for review. Next step after review is likely to load this data into test environment.

**Comment by MCatherine1994** [comment]
Hi Basil, added the Docker file for admin management, also added to the docker-compose file. I was running `docker-compose up` on my local, and get both backend api, and admin management api work fine. If we are still seeing issues with them, I'll take another look. Thanks!

**Review by ianliuwk1019 — APPROVED** [review]
Hi Basil, just wondering, after initial load-test migration in TEST environment all sequences restart at higher number from this `RESTART WITH 100000` which it should have no consequence I think. If later we need some other large load-test data (especially for role assignment xref) I guess it should be fine to insert data in between (< 100000).

**Comment by basilv** [comment]
Yes, the 'design' of the data generation load allows us to change it in the future and re-run it without affecting manaully-created data.

**Comment by basilv** [comment]
@ianliuwk1019 @MCatherine1994 This is ready for final review.

**Comment by ianliuwk1019** [comment]
Thank you so much @basilv for the comprehensive load-testing and detail procedures at readme!!
Since you have the `.js` script to regenerate data, wondering do we still need the generated `data.sql` in repo, it seems the size is quite large to checkout.

**Comment by basilv** [comment]
Yes, we need the data.sql in the repo for pulling it onto the ec2 instance for actually running the script against the database.

**Review by ianliuwk1019 — APPROVED** [review]
Thank you so much Basil!!

**Pull request merged**
