### PR TITLE
feat: #985 minor table styling tweaks

### PR DESCRIPTION
**Pull request by J0taFerreira**
Styling changes on my permissions view. https://github.com/bcgov/nr-forests-access-management/pull/1276
- env column closes to application name
- placeholder text
- removed env from application name

### CODE REVIEW

**Comment by MCatherine1994** [comment]
Hi Jota, just feel maybe the space between application and environment is too small now? and the space between enviornment and client number seems big... shall we set the space evenly? image

**Comment by MCatherine1994** [comment]
let's check the sonar cloud as well, thanks!!

**Comment by J0taFerreira** [comment]
> Hi Jota, just feel maybe the space between application and environment is too small now? and the space between enviornment and client number seems big... shall we set the space evenly? image

Hello! Sure, I can change it to space evenly

**Review by MCatherine1994 — APPROVED** [review]

**Comment by MCatherine1994** [comment]
Hi Jota, looks good, just a suggestion, maybe in the future for this kind of UI adjustment pr, it's better that you share some screenshot in the description, thanks!!

**Pull request merged**
