### PR TITLE
feat: 851 search bar in the manage permissions page

### PR DESCRIPTION
**Pull request by J0taFerreira**
- Moved  add user button (former Grant new access button) to the data Table.
- Search bar are now using the new design

### CODE REVIEW

**Review by MCatherine1994 — DISMISSED** [review]

**Comment by ianliuwk1019** [comment]
Hi Jota,
The button look pretty big and the search field "Search by keyword" is not the same height with the button.
Also there is a gap in between search and the column header row.
The button corner also look a bit strange, maybe discuss with designer if that's how it looks?
Could you adjust them? Thank you.
image

**Comment by MCatherine1994** [comment]
yeah I think with the stylesheet in the common repo, it looks better

**Comment by ianliuwk1019** [comment]
> > Hi Jota, The button look pretty big and the search field "Search by keyword" is not the same height with the button. Also there is a gap in between search and the column header row. The button corner also look a bit strange, maybe discuss with designer if that's how it looks? Could you adjust them? Thank you. image
> 
> Hello! the styling for the search field "Search by keyword" is on the common repo but I'll take a second look.

Oh, so the "search" field is in common repo, got it. My concern is strange looking on the button. So, maybe adjust button is easier than changing primevue style in common repo and leave it as is?

**Comment by MCatherine1994** [comment]
we already published a new version for the new style, the new package version is changed in #849

**Comment by J0taFerreira** [comment]
> > > Hi Jota, The button look pretty big and the search field "Search by keyword" is not the same height with the button. Also there is a gap in between search and the column header row. The button corner also look a bit strange, maybe discuss with designer if that's how it looks? Could you adjust them? Thank you. image
> > 
> > 
> > Hello! the styling for the search field "Search by keyword" is on the common repo but I'll take a second look.
> 
> Oh, so the "search" field is in common repo, got it. My concern is strange looking on the button. So, maybe adjust button is easier than changing primevue style in common repo and leave it as is?

I talked to Alison about the button styling and he said that since the search action has nothing to do with the button it should be the way it is on the design.

**Review by MCatherine1994 — APPROVED** [review]

**Pull request merged**
