### PR TITLE
feat: #1456 update role selection to use radio in table

### PR DESCRIPTION
**Pull request by NickSaglioni**
- Backend get my access api return role description;
- Regenerate client code for frontend;
- Frontend create a role table component;
- Update the two forms to use role table for role selection;

### CODE REVIEW

**Comment by MCatherine1994** [comment]
Did a little bit cleanup and styling, should be good now. Primevue does have built-in single select and multiple select in the data table component, but since our selection needs to trigger the forest client field, I feel it's okay to not use the built-in one, but write our own radio column. 

Screen Shot 2024-07-05 at 2 39 11 PM

**Comment by MCatherine1994** [comment]
Screen Shot 2024-07-05 at 2 45 31 PM
Screen Shot 2024-07-05 at 2 45 51 PM

**Comment by MCatherine1994** [comment]
Also we keep the role selection dropdown for now, cause I think we'll use it as well later for the full new design.

**Review by ianliuwk1019 — APPROVED** [review]
Fixed some code and styling. Approve this PR.

**Pull request merged**
