### PR TITLE
fix: adjusting sidenav list for better viewing

### PR DESCRIPTION
**Pull request by NickSaglioni**
Adjusting the sidenav list appearance per request:

Capture-fam-nav-bar2

### CODE REVIEW

**Comment by ianliuwk1019** [comment]
Hi @NickSaglioni,

General look good. Olga had a brief look during scrum and mentioned this behaviour is a bit strange. Would you be able to adjust it? Thank you.
Please use your judgement if this behaviour should be on common repo or not.
image
reference from Carbon: https://carbondesignsystem.com/components/UI-shell-left-panel/usage/

**Comment by NickSaglioni** [comment]
> Hi @NickSaglioni,
> 
> Generally look good. Olga had a brief look during scrum and mentioned this behaviour is a bit strange. Would you be able to adjust it? Thank you. Please use your judgement if this behaviour should be on common repo or not. image reference from Carbon: https://carbondesignsystem.com/components/UI-shell-left-panel/usage/

Hi @ianliuwk1019. Thanks for pointing it out. I have adjusted as requested. Please let me know if it looks ok. Thank you.

**Comment by ianliuwk1019** [comment]
> > Hi @NickSaglioni,
> > Generally look good. Olga had a brief look during scrum and mentioned this behaviour is a bit strange. Would you be able to adjust it? Thank you. Please use your judgement if this behaviour should be on common repo or not. image reference from Carbon: https://carbondesignsystem.com/components/UI-shell-left-panel/usage/
> 
> Hi @ianliuwk1019. Thanks for pointing it out. I have adjusted as requested. Please let me know if it looks ok. Thank you.

Hi @NickSaglioni , thanks for adjusting.
The hover on the none-selected item seem to also "bold" the text. The Carbon style sample does not do that. Could you adjust it? If common repo does not have specific one for side navigation hover styling, maybe just change it as sideNave.vue. Thanks.

**Review by MCatherine1994 — APPROVED** [review]

**Comment by MCatherine1994** [comment]
looks good, thanks Nick! My only concern is that, when there is only the "add user permission" option, the rest `<li>` elements are hidden, however they still exist, not sure from the accessibility perspective for screen reader, should we still render them? will that confuse the user? or it's okay to just hide them like this
Screen Shot 2024-04-22 at 11 58 48 AM

**Comment by ianliuwk1019** [comment]
> looks good, thanks Nick! My only concern is that, when there is only the "add user permission" option, the rest `<li>` elements are hidden, however they still exist, not sure from the accessibility perspective for screen reader, should we still render them? will that confuse the user? or it's okay to just hide them like this Screen Shot 2024-04-22 at 11 58 48 AM

That's a good observation from @MCatherine1994! It is preferable conditional rendering the elements and not just hide the element. Not sure if the reader agent actually take into account if the element is "display: none", probably not.

**Comment by MCatherine1994** [comment]
Will merge this pr, and @NickSaglioni please create a follow up ticket to make adjustment of hidden side navigation options, thanks!!

**Pull request merged**
