### PR TITLE
feat: #934 profile sidebar for mobile

### PR DESCRIPTION
**Pull request by J0taFerreira**
- Added responsiveness to profile sidebar

### CODE REVIEW

**Comment by MCatherine1994** [comment]
Hi Jota, not sure if this is by design, but when I change the window size, and at some point, my email address gets cut off
Screen Shot 2023-10-05 at 3 41 25 PM

**Comment by J0taFerreira** [comment]
> Hi Jota, not sure if this is by design, but when I change the window size, and at some point, the user information gets cut off Screen Shot 2023-10-05 at 3 41 25 PM

I'll take a look. Thanks!

**Comment by MCatherine1994** [comment]
And on the phone size, the profile icon in the header move to the next line, which is hard to click on
Screen Shot 2023-10-05 at 3 42 41 PM

**Comment by J0taFerreira** [comment]
> > Hi Jota, not sure if this is by design, but when I change the window size, and at some point, the user information gets cut off Screen Shot 2023-10-05 at 3 41 25 PM
> 
> I'll take a look. Thanks!

In what width does this occur?

**Comment by MCatherine1994** [comment]
> > > Hi Jota, not sure if this is by design, but when I change the window size, and at some point, the user information gets cut off Screen Shot 2023-10-05 at 3 41 25 PM
> > 
> > 
> > I'll take a look. Thanks!
> 
> In what width does this occur?

If I just change the browser window width directly by dragging it
Screen Shot 2023-10-06 at 11 04 15 AM

**Comment by J0taFerreira** [comment]
> > > > Hi Jota, not sure if this is by design, but when I change the window size, and at some point, the user information gets cut off Screen Shot 2023-10-05 at 3 41 25 PM
> > > 
> > > 
> > > I'll take a look. Thanks!
> > 
> > 
> > In what width does this occur?
> 
> If I just change the browser window width directly by dragging it Screen Shot 2023-10-06 at 11 04 15 AM

on the dev tools was working fine, I'll be looking into that. Thanks!

**Comment by J0taFerreira** [comment]
> > > > Hi Jota, not sure if this is by design, but when I change the window size, and at some point, the user information gets cut off Screen Shot 2023-10-05 at 3 41 25 PM
> > > 
> > > 
> > > I'll take a look. Thanks!
> > 
> > 
> > In what width does this occur?
> 
> If I just change the browser window width directly by dragging it Screen Shot 2023-10-06 at 11 04 15 AM

just fixed the media query, can you please test to see if it is fixed on your end? Thanks!

**Review by MCatherine1994 — APPROVED** [review]

**Pull request merged**
